<?php

return [
    'upload_disk' => env('EVENTS_UPLOAD_DISK', 'public'),
    'upload_temporary_urls' => (bool) env('EVENTS_UPLOAD_TEMPORARY_URLS', false),
    'upload_temporary_url_ttl_minutes' => (int) env('EVENTS_UPLOAD_TEMPORARY_URL_TTL_MINUTES', 30),
    'image_variants' => [
        'upload_max_pixels' => (int) env('EVENTS_IMAGE_UPLOAD_MAX_PIXELS', 2560),
        'upload_processing_max_bytes' => (int) env('EVENTS_IMAGE_UPLOAD_PROCESSING_MAX_BYTES', 157286400),
        'upload_quality' => (int) env('EVENTS_IMAGE_UPLOAD_QUALITY', 84),
        'upload_format' => env('EVENTS_IMAGE_UPLOAD_FORMAT', 'jpg'),
        'thumbnail_max_pixels' => (int) env('EVENTS_IMAGE_THUMBNAIL_MAX_PIXELS', 640),
        'preview_max_pixels' => (int) env('EVENTS_IMAGE_PREVIEW_MAX_PIXELS', 1600),
        'watermarked_download_max_pixels' => (int) env('EVENTS_IMAGE_WATERMARKED_DOWNLOAD_MAX_PIXELS', 2400),
        'quality' => (int) env('EVENTS_IMAGE_VARIANT_QUALITY', 82),
        'format' => env('EVENTS_IMAGE_VARIANT_FORMAT', 'jpg'),
        'watermark_text' => env('EVENTS_IMAGE_WATERMARK_TEXT', 'QR Events Preview'),
        'watermark_font' => env('EVENTS_IMAGE_WATERMARK_FONT'),
    ],
    'video_variants' => [
        'ffmpeg_binary' => env('EVENTS_VIDEO_FFMPEG_BINARY', 'ffmpeg'),
        'poster_timestamp_seconds' => (float) env('EVENTS_VIDEO_POSTER_TIMESTAMP_SECONDS', 1.2),
        'thumbnail_max_pixels' => (int) env('EVENTS_VIDEO_THUMBNAIL_MAX_PIXELS', 960),
        'preview_max_width' => (int) env('EVENTS_VIDEO_PREVIEW_MAX_WIDTH', 1280),
        'watermarked_download_max_width' => (int) env('EVENTS_VIDEO_WATERMARKED_DOWNLOAD_MAX_WIDTH', 1920),
        'quality' => (int) env('EVENTS_VIDEO_VARIANT_QUALITY', 80),
        'format' => env('EVENTS_VIDEO_VARIANT_FORMAT', 'jpg'),
        'crf' => (int) env('EVENTS_VIDEO_VARIANT_CRF', 28),
        'watermarked_download_crf' => (int) env('EVENTS_VIDEO_WATERMARKED_DOWNLOAD_CRF', 24),
        'preset' => env('EVENTS_VIDEO_VARIANT_PRESET', 'faster'),
    ],
    'default_timezone' => env('EVENTS_DEFAULT_TIMEZONE', 'Europe/Bucharest'),
    'event_date_max_months' => (int) env('EVENTS_EVENT_DATE_MAX_MONTHS', 18),
    'upload_window_starts_days_before_event' => (int) env('EVENTS_UPLOAD_WINDOW_STARTS_DAYS_BEFORE', 1),
    'upload_window_ends_days_after_event' => (int) env('EVENTS_UPLOAD_WINDOW_ENDS_DAYS_AFTER', 3),
    'pre_event_test_upload_limit' => (int) env('EVENTS_PRE_EVENT_TEST_UPLOAD_LIMIT', 10),
    'grace_days' => (int) env('EVENTS_GRACE_DAYS', 7),
    'paid_renewal_grace_days' => (int) env('EVENTS_PAID_RENEWAL_GRACE_DAYS', 7),
    'cleanup_policy' => [
        'locked_candidate_after_days' => (int) env('EVENTS_CLEANUP_LOCKED_AFTER_DAYS', 14),
        'expired_candidate_after_days' => (int) env('EVENTS_CLEANUP_EXPIRED_AFTER_DAYS', 7),
    ],
    'cleanup_digest' => [
        'hour' => (int) env('EVENTS_CLEANUP_DIGEST_HOUR', 8),
        'minute' => (int) env('EVENTS_CLEANUP_DIGEST_MINUTE', 5),
    ],
    'public_rate_limits' => [
        'read_per_minute' => (int) env('EVENTS_PUBLIC_READ_RATE_LIMIT', 120),
        'write_per_minute' => (int) env('EVENTS_PUBLIC_WRITE_RATE_LIMIT', 40),
        'upload_per_minute' => (int) env('EVENTS_PUBLIC_UPLOAD_RATE_LIMIT', 12),
    ],
    'defaults' => [
        'currency' => env('EVENTS_DEFAULT_CURRENCY', 'EUR'),
        'storage_limit_bytes' => (int) env('EVENTS_DEFAULT_STORAGE_LIMIT_BYTES', 10737418240),
        'upload_limit' => (int) env('EVENTS_DEFAULT_UPLOAD_LIMIT', 300),
        'retention_days' => (int) env('EVENTS_DEFAULT_RETENTION_DAYS', 30),
        'video_max_duration_seconds' => (int) env('EVENTS_DEFAULT_VIDEO_MAX_DURATION_SECONDS', 30),
        'photo_max_size_bytes' => (int) env('EVENTS_DEFAULT_PHOTO_MAX_SIZE_BYTES', 26214400),
        'video_max_size_bytes' => (int) env('EVENTS_DEFAULT_VIDEO_MAX_SIZE_BYTES', 524288000),
    ],
];
